apiVersion: apps/v1
kind: Deployment
metadata:
  name: metabase-deployment
  namespace: dependency-check-devsecops-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metabase
  template:
    metadata:
      labels:
        app: metabase
    spec:
      containers:
      - name: metabase
        image: metabase/metabase:latest
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "1"
            memory: "1.5Gi"
          requests:
            cpu: "500m"
            memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: metabase-service
  namespace: dependency-check-devsecops-ns
spec:
  selector:
    app: metabase
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP

