apiVersion: batch/v1
kind: Job
metadata:
  name: dpcheck-worker-job
  namespace: dependency-check-devsecops-ns
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: dpcheck-worker
    spec:
      #imagePullSecrets:
      #  - name: regcred-artifactory-harbor
      serviceAccountName: dpcheck-worker-sa
      restartPolicy: Never
      containers:
      - name: dpcheck-worker-container
        image: jtoledog/dpcheck-mongo:latest  #artifactory.vodafone.com/docker-vfes-digital-local/vf-dependency-check:latest
        env:
        - name: GITHUB_REPO_NAME
          value: "your_github_reponame"
        - name: GITHUB_URL
          value: "your_github_url"
        - name: INFLUXDB_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-secrets
              key: INFLUXDB_TOKEN
        #- name: http_proxy
        #  value: "yourproxy"
        #- name: https_proxy
        #  value: "yourproxy"
        #- name: HTTP_PROXY
        #  value: "yourproxy"
        #- name: HTTPS_PROXY
        #  value: "yourproxy"
        #volumeMounts:
        #- name: github-data
        #  mountPath: /data
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"
          requests:
            cpu: "0.5"
            memory: "1Gi"
      #volumes:
      #- name: github-data
      #  persistentVolumeClaim:
      #    claimName: dependencycheck-data-pvc