apiVersion: batch/v1
kind: Job
metadata:
  name: dpcheck-worker-job
  namespace: dependency-check-devsecops-ns
spec:
  template:
    metadata:
      labels:
        app: dpcheck-worker
    spec:
      serviceAccountName: dpcheck-worker-sa
      restartPolicy: OnFailure
      containers:
      - name: dpcheck-worker-container
        image: jtoledog/dpcheck:latest
        env:
        - name: GITHUB_REPO_NAME
          value: "your_github_reponame"
        - name: GITHUB_URL
          value: "your_github_url"
        volumeMounts:
        - name: github-data
          mountPath: /data
        resources:
          limits:
            cpu: "1.5"
            memory: "2.5Gi"
          requests:
            cpu: "0.5"
            memory: "1Gi"
      volumes:
      - name: github-data
        persistentVolumeClaim:
          claimName: dependencycheck-data-pvc