apiVersion: v1
kind: Secret
metadata:
  name: github-secrets
  namespace: dependency-check-devsecops-ns
type: Opaque
data:
  GITHUB_USER: <base64_encoded_GITHUB_USER>
  GITHUB_TOKEN: <base64_encoded_GITHUB_TOKEN>
  GITHUB_URL: <base64_encoded_GITHUB_URL>
  GITHUB_ORGANIZATION: <base64_encoded_GITHUB_ORGANIZATION>