---
# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: dependency-check-devsecops-ns
---

# RBAC for the controller
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dpcheck-controller-sa
  namespace: dependency-check-devsecops-ns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: dependency-check-devsecops-ns
  name: deployment-manager
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-manager-binding
  namespace: dependency-check-devsecops-ns
subjects:
- kind: ServiceAccount
  name: dpcheck-controller-sa
  namespace: dependency-check-devsecops-ns
roleRef:
  kind: Role
  name: deployment-manager
  apiGroup: rbac.authorization.k8s.io

# Pod Deployment
---
apiVersion: v1
kind: Namespace
metadata:
  name: dependency-check-devsecops-ns
