apiVersion: v1
kind: Secret
metadata:
  name: github-secrets
  namespace: dependency-check-devsecops-ns
type: Opaque
data:
  #GITHUB_USER: <base64_encoded_GITHUB_USER>
  #GITHUB_TOKEN: <base64_encoded_GITHUB_TOKEN>
  #GITHUB_URL: <base64_encoded_GITHUB_URL>
  #GITHUB_ORGANIZATION: <base64_encoded_GITHUB_ORGANIZATION>
  #NVD_API_KEY: <base64_encoded_NVD_API_KEY>
  #INFLUXDB_TOKEN: <base64_encoded_INFLUXDB_TOKEN>
---
apiVersion: v1
kind: Secret
metadata:
  name: regcred-artifactory-harbor
  namespace: dependency-check-devsecops-ns
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: <base64_encoded_dockerconfigjson>
---
