---
# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: dependency-check-devsecops-ns
---

# RBAC for the controller
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dpcheck-controller-sa
  namespace: dependency-check-devsecops-ns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: dependency-check-devsecops-ns
  name: deployment-manager
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-manager-binding
  namespace: dependency-check-devsecops-ns
subjects:
- kind: ServiceAccount
  name: dpcheck-controller-sa
  namespace: dependency-check-devsecops-ns
roleRef:
  kind: Role
  name: deployment-manager
  apiGroup: rbac.authorization.k8s.io
---

# Pod Deployment
---
apiVersion: v1
kind: Namespace
metadata:
  name: dependency-check-devsecops-ns

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpcheck-controller-deployment
  namespace: dependency-check-devsecops-ns
  labels:
    app: dpcheck-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dpcheck-controller
  template:
    metadata:
      labels:
        app: dpcheck-controller
    spec:
      serviceAccountName: dpcheck-controller-sa
      containers:
      - name: dpcheck-controller-container
        image: YOUR_DOCKER_IMAGE_PATH_HERE #jtoledog/polling-ado-aks
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"
          requests:
            cpu: "100m"
            memory: "100Mi"
        env:
        - name: GITHUB_USER
          valueFrom:
            secretKeyRef:
              name: github-secrets
              key: GITHUB_USER
        - name: GITHUB_TOKEN
          valueFrom:
            secretKeyRef:
              name: github-secrets
              key: GITHUB_TOKEN
        - name: GITHUB_URL
          valueFrom:
            secretKeyRef:
              name: github-secrets
              key: GITHUB_URL
        - name: GITHUB_ORGANIZATION
          valueFrom:
            secretKeyRef:
              name: github-secrets
              key: GITHUB_ORGANIZATION