apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-pv
  namespace: dependency-check-devsecops-ns
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mongodb" # Asegúrate de que esta ruta exista y tenga los permisos adecuados en tu nodo.
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: dependency-check-devsecops-ns
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
