apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: dependency-check-devsecops-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "100m"
            memory: "256Mi"
        volumeMounts:
        - name: mongo-storage
          mountPath: /data/db
      volumes:
      - name: mongo-storage
        persistentVolumeClaim:
          claimName: mongodb-pvc

---
# mongodb-service.dependency-check-devsecops-ns.svc.cluster.local:27017
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: dependency-check-devsecops-ns
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
